### ISSUE TITLE
Schematic note

### ISSUE THREAD

**Issue by timmit99** [dc42/OrmerodSensorBoard#1]
Just looking through for replacement part numbers and it seems that on the V1.2 differential sensor board schematic you did not change the Version number in the  V1.2 schematic. It still says V1.1a, September 2015.

There is no indication other than the file's path that it is ACTUALLY the V1.2 schematic.

**Comment by timmit99** [comment]
https://raw.githubusercontent.com/dc42/OrmerodSensorBoard/master/SchematicAndPCB/Mini-differential-IR/V1.0_1.1/schematic.png

https://raw.githubusercontent.com/dc42/OrmerodSensorBoard/master/SchematicAndPCB/Mini-differential-IR/V1.2/schematic.png

**Comment by dc42** [comment]
You are right, I forgot to update the version number in the text on the schematic. But it's definitely the version 1.2 schematic, it has the right part numbers for the phototransistor and IR LEDs.

**Comment by timmit99** [comment]
thanks, Just bashed into the sensor and bent one of the IR LED's back and when i tried to reorient it the legs snapped. I got 2 of them on the way from Mouser.

**Comment by dc42** [comment]
If the IR LEDs have legs then you have the version 1.0 or 1.1 board. The part numbers on the 1.2 schematic are SMD parts that won't fit your board.

**Comment by timmit99** [comment]
Yep, that's why i was checking the two versions because we have one V1.1 and one V1.2 board. That's when i noticed that the version numbering was off and just wanted to post here to avoid any further confusion. The broken board is a V1.1 so i have the sfh4141 coming. Thanks for the awesome board!
