### ISSUE TITLE
Hardcode to digital output mode

### ISSUE THREAD

**Issue by 3dlpm** [dc42/OrmerodSensorBoard#4]
Hi,

I am using the Escher 3D mini IR sensor board (V1.2) with a RUMBA board, which has a three pin Z- endstop connectors. It provides 5V on VCC, GND and has a signal input, which can be internally pulled up. Using the rumba with Marlin would easily work, but I am using the RUMBA with Klipper firmware, which runs on a separate host CPU (Raspberry Pi) and controls the RUMBA, which has a small version of firmware that executes the motion commands that the Klipper host sends it. 

I am having issues with the mini sensor board starting in analog output mode (4 LED flashes) because Klipper sometimes takes a while to start (or restart, if you changed config) so the firmware in the RUMBA does not set the internal pull-ups on the Z- signal pin on time for the mini-sensor board to detect. 
I basically have to cycle the power or disconnect the mini board connectors every time, sometimes repeatedly, until the internal pull-ups are set by klipper. It is very annoying and inconsistent to get the mini-sensor board started in digital output mode. 

I would like to simply hard code the mini sensor board so that it always starts in digital output mode. I am not a programmer and I don't have enough knowledge to modify/verify and upload the mini sensor board's firmware. Do you have a workaround or suggestion for how to hard code the sensor board to always start in digital mode?

I think this is something that should be implemented as a jumper (solder) on the board. 

Thank you

**Comment by dc42** [comment]
Hi,

Why not add an external pullup resistor between OUT and VCC? That would
be easier than reprogramming it.

Regards

David Crocker, Escher Technologies Ltd.
http://www.eschertech.com
Tel. +44 (0)20 8144 3265 or +44 (0)7977 211486

**Comment by 3dlpm** [comment]
Yes, I could try that. What value do you recommend?

**Comment by dc42** [comment]
I suggest between 20K and 100K.

On 27 June 2020 21:11:39 BST, 3dlpm <notifications@github.com> wrote:
>Yes, I could try that. What value do you recommend?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dc42/OrmerodSensorBoard/issues/4#issuecomment-650615599

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 3dlpm** [comment]
Thanks David.
It is working fine with a 39Kohm external pull-up
